import { Producto } from "../../model/Producto";

export function ProductosFalsos() 
{
    return [
        new Producto()
            .setId(1)
            .setCodigo("JM001")
            .setNombre("Catan")
            .setDescripcion("Un clásico juego de estrategia donde los jugadores compiten por colonizar y expandirse en la isla de Catan. Ideal para 3-4 jugadores y perfecto para noches de juego en familia o con amigos.")
            .setCategoria("Juegos de Mesa")
            .setPrecio(29990)
            .setImagen("/productos/catan.png")
            .setCantidad(10)
            .setMarca("Kosmos"),

        new Producto()
            .setId(2)
            .setCodigo("JM002")
            .setNombre("Carcassonne")
            .setDescripcion("Un juego de colocación de fichas donde los jugadores construyen el paisaje alrededor de la fortaleza medieval de Carcassonne. Ideal para 2-5 jugadores y fácil de aprender.")
            .setCategoria("Juegos de Mesa")
            .setPrecio(24990)
            .setImagen("/productos/carcassonne.png")
            .setCantidad(0)
            .setMarca("Hans im Glueck"),

        new Producto()
            .setId(3)
            .setCodigo("AC001")
            .setNombre("Controlador Inalámbrico Xbox Series X")
            .setDescripcion("Ofrece una experiencia de juego cómoda con botones mapeables y una respuesta táctil mejorada. Compatible con consolas Xbox y PC.")
            .setCategoria("Accesorios")
            .setPrecio(59990)
            .setImagen("/productos/control_xbox.png")
            .setDestacado(true)
            .setCantidad(10)
            .setMarca("Microsoft"),
            

        new Producto()
            .setId(4)
            .setCodigo("AC002")
            .setNombre("Auriculares Gamer HyperX Cloud II")
            .setDescripcion("Proporcionan un sonido envolvente de calidad con un micrófono desmontable y almohadillas de espuma viscoelástica para mayor comodidad durante largas sesiones de juego.")
            .setCategoria("Accesorios")
            .setPrecio(79990)
            .setImagen("/productos/audifonosCloud.png")
            .setCantidad(10)
            .setMarca("HyperX"),

        new Producto()
            .setId(5)
            .setCodigo("CO001")
            .setNombre("PlayStation 5")
            .setDescripcion("La consola de última generación de Sony, que ofrece gráficos impresionantes y tiempos de carga ultrarrápidos para una experiencia de juego inmersiva.")
            .setCategoria("Consolas")
            .setPrecio(549990)
            .setImagen("/productos/ps5.png")
            .setCantidad(10)
            .setMarca("Sony"),

        new Producto()
            .setId(6)
            .setCodigo("CG001")
            .setNombre("Notebook Gamer ASUS ROG Strix")
            .setDescripcion("Un potente equipo diseñado para los gamers más exigentes, equipado con los últimos componentes para ofrecer un rendimiento excepcional en cualquier juego.")
            .setCategoria("Computadores Gamers")
            .setPrecio(1299990)
            .setImagen("/productos/pcAsus.png")
            .setDestacado(true)
            .setCantidad(10)
            .setMarca("Asus"),

        new Producto()
            .setId(7)
            .setCodigo("SG001")
            .setNombre("Silla Gamer Secretlab Titan")
            .setDescripcion("Diseñada para el máximo confort, esta silla ofrece un soporte ergonómico y personalización ajustable para sesiones de juego prolongadas.")
            .setCategoria("Sillas Gamers")
            .setPrecio(349990)
            .setImagen("/productos/sillaGamer.png")
            .setCantidad(10)
            .setMarca("Secretlab"),

        new Producto()
            .setId(8)
            .setCodigo("MS001")
            .setNombre("Mouse Gamer Logitech G502 HERO")
            .setDescripcion("Con sensor de alta precisión y botones personalizables, este mouse es ideal para gamers que buscan un control preciso y personalización.")
            .setCategoria("Accesorios")
            .setPrecio(49990)
            .setImagen("/productos/mouseLogitech.png")
            .setCantidad(10)
            .setMarca("Logitech"),

        new Producto()
            .setId(9)
            .setCodigo("MP001")
            .setNombre("Mousepad Razer Goliathus Extended Chroma")
            .setDescripcion("Ofrece un área de juego amplia con iluminación RGB personalizable, asegurando una superficie suave y uniforme para el movimiento del mouse.")
            .setCategoria("Accesorios")
            .setPrecio(29990)
            .setImagen("/productos/mousepad.png")
            .setCantidad(10)
            .setMarca("Razer"),

        new Producto()
            .setId(10)
            .setCodigo("RO001")
            .setNombre("Polera Gamer Personalizada 'Level-Up'")
            .setDescripcion("Una camiseta cómoda y estilizada, con la posibilidad de personalizarla con tu gamer tag o diseño favorito.")
            .setCategoria("Ropa")
            .setPrecio(19990)
            .setImagen("/productos/Polera-personalizada.png")
            .setDestacado(true)
            .setCantidad(10)
            .setMarca("Propia"),

        new Producto()
            .setId(11)
            .setCodigo("SD-01")
            .setNombre("Baraja Rokket")
            .setDescripcion("Baraja Rokket, es una estrategia pura constando de cartas genericas y de el propio arquetipo")
            .setCategoria("TCG")
            .setPrecio(99990)
            .setDestacado(true)
            .setImagen("/productos/cohette.jpg")
            .setCantidad(1)
            .setMarca("Propia")
            .setOferta(1),

        new Producto()
            .setId(12)
            .setCodigo("JM003")
            .setNombre("Dixit")
            .setDescripcion("Un juego visual y creativo donde los jugadores deben adivinar qué carta ilustra mejor una frase dada. Ideal para toda la familia.")
            .setCategoria("Juegos de Mesa")
            .setPrecio(27990)
            .setImagen("/productos/dixit.png")
            .setCantidad(10)
            .setMarca("Libellud")
            .setOferta(0.9),

        new Producto()
            .setId(13)
            .setCodigo("AC003")
            .setNombre("Teclado Mecánico Redragon Kumara K552")
            .setDescripcion("Teclado compacto con switches mecánicos y retroiluminación RGB, ideal para gamers que buscan rendimiento y estilo.")
            .setCategoria("Accesorios")
            .setPrecio(49990)
            .setImagen("/productos/tecladoRedragon.png")
            .setCantidad(10)
            .setMarca("Redragon"),

        new Producto()
            .setId(14)
            .setCodigo("CO002")
            .setNombre("Nintendo Switch OLED")
            .setDescripcion("La consola híbrida de Nintendo con una vibrante pantalla OLED de 7 pulgadas, perfecta para jugar en casa o en movimiento.")
            .setCategoria("Consolas")
            .setPrecio(429990)
            .setImagen("/productos/switchOLED.png")
            .setDestacado(true)
            .setCantidad(10)
            .setMarca("Nintendo"),

        new Producto()
            .setId(15)
            .setCodigo("SG002")
            .setNombre("Silla Gamer Cougar Armor One")
            .setDescripcion("Silla ergonómica con soporte lumbar y diseño deportivo, ideal para largas sesiones frente al computador.")
            .setCategoria("Sillas Gamers")
            .setPrecio(279990)
            .setImagen("/productos/sillaCougar.png")
            .setCantidad(10)
            .setMarca("Cougar"),

        new Producto()
            .setId(16)
            .setCodigo("CG002")
            .setNombre("PC Gamer HP Omen 16")
            .setDescripcion("Notebook gamer de alto rendimiento con tarjeta gráfica RTX y pantalla de alta tasa de refresco.")
            .setCategoria("Computadores Gamers")
            .setPrecio(1399990)
            .setImagen("/productos/pcOmen.png")
            .setCantidad(10)
            .setMarca("HP"),

        new Producto()
            .setId(17)
            .setCodigo("MS002")
            .setNombre("Mouse Razer DeathAdder V2")
            .setDescripcion("Mouse ergonómico con sensor óptico de alta precisión, diseñado para brindar velocidad y comodidad en juegos competitivos.")
            .setCategoria("Accesorios")
            .setPrecio(59990)
            .setImagen("/productos/mouseRazer.png")
            .setCantidad(10)
            .setMarca("Razer"),

        new Producto()
            .setId(18)
            .setCodigo("MP002")
            .setNombre("Mousepad SteelSeries QcK Heavy")
            .setDescripcion("Superficie microtexturizada de tela con base de goma antideslizante para máxima precisión y estabilidad.")
            .setCategoria("Accesorios")
            .setPrecio(24990)
            .setImagen("/productos/mousepadSteelseries.png")
            .setCantidad(10)
            .setMarca("SteelSeries"),

        new Producto()
            .setId(19)
            .setCodigo("RO002")
            .setNombre("Polerón Gamer 'Respawn Mode'")
            .setDescripcion("Polerón cómodo de algodón con diseño gamer minimalista, ideal para jugar o salir con estilo.")
            .setCategoria("Ropa")
            .setPrecio(29990)
            .setImagen("/productos/poleronRespawn.png")
            .setCantidad(10)
            .setMarca("Propia"),

        new Producto()
            .setId(20)
            .setCodigo("TCG002")
            .setNombre("Baraja Dragunity Legion")
            .setDescripcion("Un mazo poderoso centrado en la invocación rápida de dragones y sinergias aéreas. Ideal para jugadores intermedios.")
            .setCategoria("TCG")
            .setPrecio(89990)
            .setImagen("/productos/dragunity.jpg")
            .setCantidad(3)
            .setMarca("Konami"),

        new Producto()
            .setId(21)
            .setCodigo("TCG003")
            .setNombre("Baraja Cyber Dragon")
            .setDescripcion("Mazo estructurado con cartas icónicas del arquetipo Cyber Dragon, ideal para duelos de poder y fusión.")
            .setCategoria("TCG")
            .setPrecio(94990)
            .setImagen("/productos/cyberdragon.jpg")
            .setDestacado(true)
            .setCantidad(3)
            .setMarca("Konami"),

        new Producto()
            .setId(22)
            .setCodigo("CO003")
            .setNombre("Xbox Series X")
            .setDescripcion("La consola más potente de Microsoft con soporte para 4K real, tiempos de carga rápidos y retrocompatibilidad con miles de títulos.")
            .setCategoria("Consolas")
            .setPrecio(519990)
            .setImagen("/productos/xboxSeriesX.png")
            .setCantidad(10)
            .setMarca("Microsoft"),

        new Producto()
            .setId(23)
            .setCodigo("CO004")
            .setNombre("Nintendo Switch Lite")
            .setDescripcion("Versión compacta y portátil de la consola híbrida de Nintendo, perfecta para jugar en movimiento.")
            .setCategoria("Consolas")
            .setPrecio(239990)
            .setImagen("/productos/switchLite.png")
            .setCantidad(10)
            .setMarca("Nintendo"),

        new Producto()
            .setId(24)
            .setCodigo("AC004")
            .setNombre("Base de Carga DualSense PS5")
            .setDescripcion("Permite cargar simultáneamente dos controles DualSense, manteniendo tu zona de juego ordenada y lista para la acción.")
            .setCategoria("Accesorios")
            .setPrecio(34990)
            .setImagen("/productos/baseCargaDualsense.png")
            .setCantidad(10)
            .setMarca("Sony"),

        new Producto()
            .setId(25)
            .setCodigo("RO003")
            .setNombre("Gorra 'Game Over'")
            .setDescripcion("Gorra ajustable con diseño bordado 'Game Over', ideal para gamers que quieren llevar su estilo fuera de la pantalla.")
            .setCategoria("Ropa")
            .setPrecio(14990)
            .setImagen("/productos/gorraGameOver.png")
            .setCantidad(15)
            .setMarca("Propia"),

        new Producto()
            .setId(26)
            .setCodigo("RO004")
            .setNombre("Taza Gamer RGB")
            .setDescripcion("Taza con diseño termocromático que cambia de color al contacto con líquidos calientes. Perfecta para café o energía extra.")
            .setCategoria("Merchandising")
            .setPrecio(9990)
            .setImagen("/productos/tazaRGB.png")
            .setCantidad(20)
            .setMarca("Razer"),

        new Producto()
            .setId(27)
            .setCodigo("SG003")
            .setNombre("Silla Gamer Razer Iskur")
            .setDescripcion("Silla ergonómica premium con soporte lumbar ajustable y materiales de alta calidad. Ideal para sesiones intensas de juego.")
            .setCategoria("Sillas Gamers")
            .setPrecio(429990)
            .setImagen("/productos/sillaRazer.png")
            .setDestacado(true)
            .setCantidad(5)
            .setMarca("Razer"),

        new Producto()
            .setId(28)
            .setCodigo("MS003")
            .setNombre("Mouse Inalámbrico Logitech G Pro X Superlight")
            .setDescripcion("Ultraligero y sin cables, diseñado para eSports. Precisión máxima con el sensor HERO 25K.")
            .setCategoria("Accesorios")
            .setPrecio(129990)
            .setImagen("/productos/mouseProX.png")
            .setCantidad(10)
            .setMarca("Logitech"),

        new Producto()
            .setId(29)
            .setCodigo("AC005")
            .setNombre("Micrófono HyperX QuadCast S")
            .setDescripcion("Micrófono USB con iluminación RGB y excelente calidad de sonido, ideal para streamers y creadores de contenido.")
            .setCategoria("Accesorios")
            .setPrecio(139990)
            .setImagen("/productos/microfonoQuadcast.png")
            .setDestacado(true)
            .setCantidad(5)
            .setMarca("HyperX"),

        new Producto()
            .setId(30)
            .setCodigo("CG003")
            .setNombre("Notebook Gamer MSI Katana")
            .setDescripcion("Portátil con GPU RTX, gran rendimiento térmico y diseño elegante. Ideal para jugar y crear contenido.")
            .setCategoria("Computadores Gamers")
            .setPrecio(1249990)
            .setImagen("/productos/pcMSI.png")
            .setCantidad(6)
            .setMarca("MSI"),

        new Producto()
            .setId(31)
            .setCodigo("JM004")
            .setNombre("Terraforming Mars")
            .setDescripcion("Los jugadores compiten por hacer habitable el planeta Marte a través de proyectos científicos, corporaciones y estrategias de desarrollo.")
            .setCategoria("Juegos de Mesa")
            .setPrecio(49990)
            .setImagen("/productos/terraformingMars.png")
            .setCantidad(10)
            .setMarca("Stronghold Games"),

        new Producto()
            .setId(32)
            .setCodigo("JM005")
            .setNombre("Ticket to Ride: Europa")
            .setDescripcion("Construye rutas de tren a lo largo de Europa en este juego de estrategia y aventura familiar. Fácil de aprender y adictivo.")
            .setCategoria("Juegos de Mesa")
            .setPrecio(34990)
            .setImagen("/productos/ticketToRide.png")
            .setCantidad(10)
            .setMarca("Days of Wonder"),

        new Producto()
            .setId(33)
            .setCodigo("AC006")
            .setNombre("Capturadora Elgato HD60 X")
            .setDescripcion("Captura video en 1080p60 HDR10, ideal para grabar o transmitir tus partidas desde consola o PC.")
            .setCategoria("Accesorios")
            .setPrecio(219990)
            .setImagen("/productos/elgatoHD60.png")
            .setCantidad(5)
            .setMarca("Elgato"),

        new Producto()
            .setId(34)
            .setCodigo("MP003")
            .setNombre("Mousepad Corsair MM300 Extended")
            .setDescripcion("Superficie optimizada para precisión y control, con bordes cosidos y base antideslizante.")
            .setCategoria("Accesorios")
            .setPrecio(29990)
            .setImagen("/productos/mousepadCorsair.png")
            .setCantidad(10)
            .setMarca("Corsair"),

        new Producto()
            .setId(35)
            .setCodigo("RO005")
            .setNombre("Sudadera 'Eat. Sleep. Game. Repeat.'")
            .setDescripcion("Sudadera cómoda de algodón con estampado gamer. Perfecta para relajarse o jugar con estilo.")
            .setCategoria("Ropa")
            .setPrecio(24990)
            .setImagen("/productos/sudaderaGamer.png")
            .setCantidad(10)
            .setMarca("Propia")
            .setOferta(0.3),

        new Producto()
            .setId(36 )
            .setCodigo("ME001")
            .setNombre("Figura Coleccionable Link (Zelda BOTW)")
            .setDescripcion("Figura detallada de Link con su arco, inspirada en 'The Legend of Zelda: Breath of the Wild'. Ideal para coleccionistas.")
            .setCategoria("Merchandising")
            .setPrecio(59990)
            .setImagen("/productos/linkFigura.png")
            .setCantidad(8)
            .setMarca("Nintendo")
            .setOferta(0.5),

            ];
}